# Google App Engine Configuration for Content Palette
runtime: nodejs20

instance_class: F2

env_variables:
  NODE_ENV: "production"

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always
    
  - url: /.*
    script: auto
    secure: always
