# Google App Engine configuration (alternative to Cloud Run)
runtime: nodejs20

env: standard

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.6

env_variables:
  NODE_ENV: 'production'
  NEXT_TELEMETRY_DISABLED: '1'

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
